
CUDA_VISIBLE_DEVICES=2 python empirical_test.py metaroom resnet50 diff_resolvable_tz data/predict/save_all_new/resnet50/tz/tv_noise_0.01_0.75_uniform100 --batch 1 --noise_sd 0.75  --pretrain ../certifiable/models/all/resnet50/all/tv_noise_0.75/checkpoint.pth.tar  --uniform --using_save --saved_path ../certifiable/data/alias_save/metaroom/tz/tv_noise_0.01_7000_new_imgs_fixed_mew
CUDA_VISIBLE_DEVICES=3 python empirical_test.py metaroom resnet50 diff_resolvable_tz data/predict/save_all_new/resnet50/tz/tv_noise_0.01_0.75_uniform5 --batch 1 --noise_sd 0.75  --pretrain ../certifiable/models/all/resnet50/all/tv_noise_0.75/checkpoint.pth.tar  --uniform --using_save --saved_path ../certifiable/data/alias_save/metaroom/tz/tv_noise_0.01_7000_new_imgs_fixed_mew --sample_num 5
CUDA_VISIBLE_DEVICES=2 python empirical_test.py metaroom resnet50 diff_resolvable_tz data/predict/save_all_new/resnet50/tz/tv_noise_0.01_0.75_benign --batch 1 --noise_sd 0.75  --pretrain ../certifiable/models/all/resnet50/all/tv_noise_0.75/checkpoint.pth.tar  --uniform --using_save --saved_path ../certifiable/data/alias_save/metaroom/tz/tv_noise_0.01_7000_new_imgs_fixed_mew --benign # 0.308
CUDA_VISIBLE_DEVICES=2 python empirical_test.py metaroom resnet50 diff_resolvable_tz data/predict/save_all_new/resnet50/tz/tv_noise_0.01_0.5_diffu_benign --batch 1 --noise_sd 0.5  --pretrain ../certifiable/models/metaroom/resnet50/all_diffusion/tv_noise_0.5/checkpoint.pth.tar  --uniform --using_save --saved_path ../certifiable/data/alias_save/metaroom/tz/tv_noise_0.01_7000_new_imgs_fixed_mew --benign

CUDA_VISIBLE_DEVICES=3 python empirical_test.py metaroom resnet50 diff_resolvable_tz data/predict/save_all_new/resnet50/tz/tv_noise_0.02_0.75_uniform100 --batch 1 --noise_sd 0.75  --pretrain ../certifiable/models/all/resnet50/all/tv_noise_0.75/checkpoint.pth.tar  --uniform --using_save --saved_path ../certifiable/data/alias_save/metaroom/tz/tv_noise_0.02_7000_new_imgs_fixed_mew
CUDA_VISIBLE_DEVICES=2 python empirical_test.py metaroom resnet50 diff_resolvable_tz data/predict/save_all_new/resnet50/tz/tv_noise_0.02_0.75_uniform5 --batch 1 --noise_sd 0.75  --pretrain ../certifiable/models/all/resnet50/all/tv_noise_0.75/checkpoint.pth.tar  --uniform --using_save --saved_path ../certifiable/data/alias_save/metaroom/tz/tv_noise_0.02_7000_new_imgs_fixed_mew --sample_num 5
CUDA_VISIBLE_DEVICES=3 python empirical_test.py metaroom resnet50 diff_resolvable_tz data/predict/save_all_new/resnet50/tz/tv_noise_0.02_0.75_benign --batch 1 --noise_sd 0.75  --pretrain ../certifiable/models/all/resnet50/all/tv_noise_0.75/checkpoint.pth.tar  --uniform --using_save --saved_path ../certifiable/data/alias_save/metaroom/tz/tv_noise_0.02_7000_new_imgs_fixed_mew --benign

CUDA_VISIBLE_DEVICES=2 python empirical_test.py metaroom resnet101 diff_resolvable_tz data/predict/save_all_new/resnet101/tz/tv_noise_0.01_0.75_uniform100 --batch 1 --noise_sd 0.75  --pretrain ../certifiable/models/all/resnet101/all/tv_noise_0.75/checkpoint.pth.tar  --uniform --using_save --saved_path ../certifiable/data/alias_save/metaroom/tz/tv_noise_0.01_7000_new_imgs_fixed_mew
CUDA_VISIBLE_DEVICES=3 python empirical_test.py metaroom resnet101 diff_resolvable_tz data/predict/save_all_new/resnet101/tz/tv_noise_0.01_0.75_uniform5 --batch 1 --noise_sd 0.75  --pretrain ../certifiable/models/all/resnet101/all/tv_noise_0.75/checkpoint.pth.tar  --uniform --using_save --saved_path ../certifiable/data/alias_save/metaroom/tz/tv_noise_0.01_7000_new_imgs_fixed_mew --sample_num 5
CUDA_VISIBLE_DEVICES=2 python empirical_test.py metaroom resnet101 diff_resolvable_tz data/predict/save_all_new/resnet101/tz/tv_noise_0.01_0.75_benign --batch 1 --noise_sd 0.75  --pretrain ../certifiable/models/all/resnet101/all/tv_noise_0.75/checkpoint.pth.tar  --uniform --using_save --saved_path ../certifiable/data/alias_save/metaroom/tz/tv_noise_0.01_7000_new_imgs_fixed_mew --benign # 0.503
CUDA_VISIBLE_DEVICES=2 python empirical_test.py metaroom resnet101 diff_resolvable_tz data/predict/save_all_new/resnet101/tz/tv_noise_0.01_0.5_diffu_benign --batch 1 --noise_sd 0.5  --pretrain ../certifiable/models/metaroom/resnet101/all_diffusion/tv_noise_0.5/checkpoint.pth.tar  --uniform --using_save --saved_path ../certifiable/data/alias_save/metaroom/tz/tv_noise_0.01_7000_new_imgs_fixed_mew --benign
 
CUDA_VISIBLE_DEVICES=3 python empirical_test.py metaroom resnet101 diff_resolvable_tz data/predict/save_all_new/resnet101/tz/tv_noise_0.02_0.75_uniform100 --batch 1 --noise_sd 0.75  --pretrain ../certifiable/models/all/resnet101/all/tv_noise_0.75/checkpoint.pth.tar  --uniform --using_save --saved_path ../certifiable/data/alias_save/metaroom/tz/tv_noise_0.02_7000_new_imgs_fixed_mew
CUDA_VISIBLE_DEVICES=2 python empirical_test.py metaroom resnet101 diff_resolvable_tz data/predict/save_all_new/resnet101/tz/tv_noise_0.02_0.75_uniform5 --batch 1 --noise_sd 0.75  --pretrain ../certifiable/models/all/resnet101/all/tv_noise_0.75/checkpoint.pth.tar  --uniform --using_save --saved_path ../certifiable/data/alias_save/metaroom/tz/tv_noise_0.02_7000_new_imgs_fixed_mew --sample_num 5
CUDA_VISIBLE_DEVICES=3 python empirical_test.py metaroom resnet101 diff_resolvable_tz data/predict/save_all_new/resnet101/tz/tv_noise_0.02_0.75_benign --batch 1 --noise_sd 0.75  --pretrain ../certifiable/models/all/resnet101/all/tv_noise_0.75/checkpoint.pth.tar  --uniform --using_save --saved_path ../certifiable/data/alias_save/metaroom/tz/tv_noise_0.02_7000_new_imgs_fixed_mew --benign

CUDA_VISIBLE_DEVICES=0 python diff_certify_save.py metaroom diff_resolvable_tz  models/metaroom/resnet50/all_diffusion/tv_noise_0.5/checkpoint.pth.tar 0.5 data/alias_save/metaroom/tz/tv_noise_0.01_7000_new data/predict/save_all_new_100/resnet50/tz/tv_noise_0.01_0.5_1000_1k_diffusion_trained_39  --batch 64  --partial 0.01 --saved_path data/alias_save/metaroom/tz/tv_noise_0.01_7000_new_imgs_fixed_mew --denoiser diffusion --N_partitions 1001 --N0 100 --N 1000